### ISSUE TITLE
Support for div  `overflow-y: scroll;`

### ISSUE THREAD

**Issue by rngtng** [thesmart/jquery-scrollspy#2]
thanks for this great plugin. I just tested it, but unfortunately it doesn't work on content which is within a div with style `overflow-y: scroll;` maybe because the viewport sit's on window? any idea how to get this working??

**Comment by thesmart** [comment]
Sorry for the late reply.

Yeah, currently I am only observing the window viewport.  Might be able to adapt it to have a different "viewport".  I hadn't considered this feature.

**Comment by thesmart** [comment]
Hello. I've added div overflow support to the new 0.2.0 beta: 
https://github.com/thesmart/jquery-scrollspy/tree/0.2.0

If you get a chance, give it a go. I'd appreciate getting eyes and any feedback about it.
