### ISSUE TITLE
Option for custom sized viewport rectangle for detecting elements

### ISSUE THREAD

**Issue by ericandrewlewis** [thesmart/jquery-scrollspy#3]
The entire viewport of the browser is currently used as the field; elements that enter this area have "entered" to use the terminology of this library. 

I'm in need of offsets here - I would like to say that elements only enter when they've been scrolled half way up the viewport. This is not possible with the current design of code, and would probably need a bit of refactoring.

Preferably this would be something you could define in the options when calling the scrollSpy() method.

**Comment by thesmart** [comment]
This would be really great, but I don't currently have bandwidth to add it. Should be simple to add to the options set.  Send me a pull request and I'll look into it.

**Comment by thesmart** [comment]
Offsets have been added, will commit soon.
