### ISSUE TITLE
Adjusting offset 

### ISSUE THREAD

**Issue by guyisra** [thesmart/jquery-scrollspy#6]
Is there a way to set an offset of the element before/after entering the screen?

I am having trouble with spying on elements which are shorter than the window height and the next element enters - then the next element takes precendence over the element that was already in screen and didn't exit

**Comment by thesmart** [comment]
I believe you are confusing this library with the scrollspy feature that Bootstrap provides.  If an element enters the viewport, it will stay "entered" until it leaves the viewport.  It's not like Bootstrap scrollspy, where only the latest element to enter is "entered".

You could write a layer on top of this library to do that easily.  Just keep track of the latest element to enter and invoke your own custom event.
